#!/bin/bash

get_clock_face() {
    h=$( date '+%I' )
    m=$( date '+%M' )
    
    if [ 30 -le $m ]; then 
      charoff=$((0x9b+10#$h))
    else
      charoff=$((0x8f+10#$h));
    fi

    # printf '%x' "$charoff" # 
    printf "\xf0\x9f\x95\x$(printf '%x' $charoff )"
}

# date '+%y %b %d (%a) %I:%M%p'
printf "📅 $(date '+%b %d (%a)') $(get_clock_face) $(date '+%I:%M') \n"

case $BLOCK_BUTTON in
	# 1) pgrep -x dunst >/dev/null && notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -D ~/.config/calcurse -d3)" ;;
	1) notify-send "This Month"  "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")"  ;;

	2) "$TERMINAL" -e calcurse -D ~/.config/calcurse ;;
	3) pgrep -x dunst >/dev/null && notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
esac

# 🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛🕜🕝🕞🕟🕠🕡🕢🕣🕤🕥🕦🕧
# printf "\xf0\x9f\x95\x90"
# printf "\xf0\x9f\x95\x91"
# printf "\xf0\x9f\x95\x92"
# printf "\xf0\x9f\x95\x93"
# printf "\xf0\x9f\x95\x94"
# printf "\xf0\x9f\x95\x95"
# printf "\xf0\x9f\x95\x96"
# printf "\xf0\x9f\x95\x97"
# printf "\xf0\x9f\x95\x98"
# printf "\xf0\x9f\x95\x99"
# printf "\xf0\x9f\x95\x9a"
# printf "\xf0\x9f\x95\x9b"
# printf "\xf0\x9f\x95\x9c"
# printf "\xf0\x9f\x95\x9d"
# printf "\xf0\x9f\x95\x9e"
# printf "\xf0\x9f\x95\x9f"
# printf "\xf0\x9f\x95\xa0"
# printf "\xf0\x9f\x95\xa1"
# printf "\xf0\x9f\x95\xa2"
# printf "\xf0\x9f\x95\xa3"
# printf "\xf0\x9f\x95\xa4"
# printf "\xf0\x9f\x95\xa5"
# printf "\xf0\x9f\x95\xa6"
# printf "\xf0\x9f\x95\xa7"
