#!/bin/bash

case $BLOCK_BUTTON in
	# 1) setsid "$TERMINAL" -e pulsemixer > /dev/null & ;;
	1) gnome-control-center sound ;;
	2) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
	3) pgrep -x dunst >/dev/null && notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change."
esac

# [ "$(pulsemixer --get-mute)" = "1" ] && printf "🔇\\n" && exit
if [[ "$(pactl get-sink-mute 0)" == *"yes" ]]; then
  printf "🔇\\n" && exit
fi

# echo "'$(pactl get-sink-mute 0)'"

# vol=$(awk '{print $1}' <(pulsemixer --get-volume))
vol=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s\n" "$icon" "$vol"
