#!/bin/sh

# Toggle floating dropdown terminal in i3, or start if non-existing.
# $1 is	the script run in the terminal.
# All other args are terminal settings.
# Terminal names are in dropdown_* to allow easily setting i3 settings.

[ -z "$1" ] && exit

if xwininfo -tree -root | grep "(\"dropdown_$1\" ";
then
	echo "Window detected."
	i3 "[instance=\"dropdown_$1\"] scratchpad show;"
      #  [instance=\"dropdown_$1\"] move position center"
else
	echo "Window not detected... spawning."
	case $TERMINAL in 
		"st") echo "st -n dropdown_$1 -e $@" | ${SHELL:-"/bin/sh"} ;;
		"urxvt") echo "urxvt -name dropdown_$1 -e $@" | ${SHELL:-"/bin/sh"} ;;
    "kitty") # NOTE: This requies .bashrc to run ONSTART if set
          # echo "ONSTART=\"$@\" kitty --name dropdown_$1" | ${SHELL:-"/bin/sh"} ;
          echo "ONSTART=\"$@\" kitty --name dropdown_$1" | ${SHELL:-"/bin/sh"} ;;
          # echo "kitty -e $@ --name dropdown_$1" | ${SHELL:-"/bin/sh"} ;;
		*) notify-send "$TERMINAL is not suported!";;
	esac
fi
