#!/bin/bash

[ -z "$1" ] && echo "No direction provided" && exit 1
distanceStr=$( [ -z "$2" ] && "50px or 2ppt" || echo "$2" )

moveChoice() {
	if [ $(i3-msg resize "$1" "$2" "$distanceStr" | grep '"success":true') ];
	then i3-msg resize "$1" "$4" "$distanceStr"
    else i3-msg resize "$3" "$4" "$distanceStr"
    fi 
}

case $1 in
  up)    moveChoice grow   up   shrink down  ;;
  down)  moveChoice shrink up   grow   down  ;;
  left)  moveChoice grow   left shrink right ;;
  right) moveChoice shrink left grow   right ;;
esac

