#!/bin/bash

# sudo apt update -y
# sudo apt --fix-broken install
# 
# sudo apt install -y neovim rxvt-unicode
# sudo apt install -y dunst unclutter libnotify-bin
# sudo apt install -y suckless-tools feh 
# sudo apt install -y sxiv
# sudo apt install -y gnome-screenshot
# 
# sudo apt install -y fonts-dejavu fonts-font-awsome fonts-emojione 

source .essence_func
# [ -f /etc/sudoers.d/np-pass ] sudoers_nopass
# install_i3_gaps
# install_google_chorme

# # Axilary
# # [ -f ~/.config/wall.png ] || setbg ~/.myconf/wall.jpg;
# [ -a ~/.trash ] || ln -s ~/.local/share/Trash/files/ ~/.trash;

