#!/bin/sh

myconf=$HOME/.myconf

gen_symlinks() 
{
    for v in `ls -A $myconf/$1`; do
        vv="$2/$v";
        if [ -f $vv ]; then
            [ -L $vv ] || echo "File $vv alredy exists!"; 
        elif [ -d $vv ]; then
            [ -L $vv ] || echo "Dir $vv alredy exists!"; 
        else	
            ln -fs "$myconf/$1/$v" $vv;
        fi;
    done
}

gen_symlinks home	$HOME;
gen_symlinks config	$HOME/.config;
gen_symlinks share	$HOME/.local/share;

gen_symlinks bin	/usr/local/bin;
