#!/bin/sh

myconf=$HOME/.myconf

ln -fs "$myconf/.bash_aliases" "$HOME/.bash_aliases"
ln -fs "$myconf/.bashrc" "$HOME/.bashrc"
ln -fs "$myconf/.profile" "$HOME/.profile"

ln -s "$myconf/.bin"  "$HOME/.bin"
ln -s "$myconf/.scripts"  "$HOME/.scripts"

for v in `ls $myconf/.config`; do
    ln -s "$myconf/.config/$v" "$HOME/.config/$v";
done
