#!/bin/sh
PID=$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)
# echo $PID
PID=$(echo "$(pstree -lpA "$PID" | tail -n 1)" | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')
# echo $PID
# echo $(readlink /proc/$PID/cwd)
cd "$(readlink /proc/"$PID"/cwd)"
"$TERMINAL" > /dev/null 2>&1 &
