#!/bin/sh
# Sets the background. If given an argument, will set file as background.

#[ ! -z "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed." xwallpaper --zoom ~/.config/wall.png

[ ! -z "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed." && feh --bg-fill ~/.config/wall.png

# feh --randomize --bg-fill ~/Pictures/Wallpapers/*
