#!/bin/sh

level="$( cat '/sys/class/backlight/intel_backlight/brightness' )"
maxlevel="$( cat '/sys/class/backlight/intel_backlight/max_brightness' )"

while getopts ":i:d:" opt; do case ${opt} in
	i ) level=$(( $level + $OPTARG )) ;;
	d ) level=$(( $level - $OPTARG )) ;;
	\? ) echo "Usage: cmd [-i] <increse> [-d] <decrese>" && exit 0 ;;
esac done

[ $level -gt $maxlevel ] && level=$maxlevel;
[ $level -lt         0 ] && level=0;

echo $level | tee /sys/class/backlight/intel_backlight/brightness
cat /sys/class/backlight/intel_backlight/brightness
