#!/bin/bash

# varfile="$VARS/brightness_var"
varfile="/home/noko/.vars/brightness_var"

if [ -f "$varfile" ]; then
	. "$varfile"
fi

[ -z $level ] && level=70

while getopts ":i:d:" opt; do
	case ${opt} in
		i ) level=$(( $level + $OPTARG ))
		  ;;
		d ) level=$(( $level - $OPTARG ))
		  ;;
		\? ) echo "Usage: cmd [-i] <increse> [-d] <decrese>"
		  ;;
	esac
done

[ $level -gt 150 ] && level=150;
[ $level -lt   0 ] && level=0;

declare -p level | cut -d ' ' -f 3- > $varfile

brightness_level="$( printf %.2f\\n $(( $level  ))e-2 )"
screenname=$(xrandr | grep " connected" | cut -f1 -d" ")
xrandr --output $screenname --brightness $brightness_level;
echo $level
