#!/bin/sh

bmfile="$HOME/.config/gg-bookmarks"

X=$( sed "s/\s*#.*$//;/^\s*$/d" $bmfile | cut -d' ' -f1 | dmenu )
cc=$( sed "s/\s*#.*$//;/^\s*$/d" $bmfile | grep "^$X " | cut -d' ' -f2- )  

echo $cc
[ -z $X ] || [ -z $cc ] || eval "google-chrome $cc"

