#!/bin/bash

# date +"%T"
# cdlogfile_tag=$(($(date +%s%N)/1000000))
# cdlogfile=~/.cache/cdlogs/$cdlogfile_tag

function cd() {
	if [ "$1" == "_" ]; then
		cd "$( tail -n 1 $cdlogfile )"; pwd; ls;
		sed -i '$ d' $cdlogfile
	else
		loc=$(pwd);	
		cd "$@"; 
		if [ "$loc" != "$(pwd)" ]; then
			pwd; ls;
			echo "$loc" >> $cdlogfile;
		fi
	fi 
}
