#!/bin/sh

# TODO bmdir="$HOME/.config/dmenu_run.wlist.d"
# brfile="$HOME/.config/gg-bookmarks"

bmfile="$HOME/.config/dml"

cmt() {
    sed 's/\s*[^"\]#.*$\|^#.*$//;/^\s*$/d' "$1" | \
        sed ':a;N;$!ba;s/\\\n\s*//g' 
}

run() {
    [ -z $1 ] && exit
    
    l=$(cmt $bmfile | grep "^$1$\|^$1 ")
    [ -z $l ] && notify-send "keyword '$1' was not found"

    c=$(echo $l | cut -d' ' -f2- )
    
    [ -z $c ] && c=$1
    echo $c

    echo $c | ${SHELL:-"/bin/sh"} &
}

dmenu_search() {
  cmt $bmfile | \
        cut -d' ' -f1 | dmenu 
}

if [ -z $1 ]; then 
    run $(dmenu_search) 
else
    run "$1"
fi


# < ~/.config/dmenu_run.wlist dmenu "$@" | ${SHELL:-"/bin/sh"} &
