#!/bin/bash

cdir=$HOME/.i3/
gdir=$HOME/.i3/gen-files/

rmc() { sed -e '/^\s*$/d;s/\s*$//;/^\s*#/d;s/\s*#%.*$//'; }

ws_names_i3() {
    awk '{ 
        split($0, a, "\"")
        printf "set $"$1"\t\""a[2]"\"\n"
    }' > $gdir/ws-names.i3
}

ws_names_sh() {
    awk '{
        split($0, a, "\"")
        printf "export "$1"=\""a[2]"\"\n"
    }' > $gdir/ws-names.sh
}

ws_keys() {
    sed '/"\s*$/d;s/\s*".*"\s*/ /' | awk '{ 
        printf "bindsym $mod+"$2"  \t\tworkspace $"$1"\n"
        printf "bindsym $mod+Ctrl+"$2" \tmove workspace $"$1"\n"
        printf "bindsym $mod+Shift+"$2" \tmove workspace $"$1
        printf "; workspace $"$1"\n"
        }' > $gdir/ws-keys.i3
}

key_conflicts() {
    conflicts="$(sort | uniq -c | grep -v '^ *1 ')"
    [ -n "$conflicts" ] && { printf "Conflicts:\n$conflicts\n"; }
}

keybindings() {
    grep ^bindsym \
        | sed 's/\t/ /' \
        | cut -d' ' -f 2 
}

< $cdir/ws-names rmc \
    > "$gdir/ws-names"

< "$gdir/ws-names" ws_names_i3
< "$gdir/ws-names" ws_names_sh
< "$gdir/ws-names" ws_keys

cat $cdir/base.i3 	   \
    $gdir/ws-names.i3  \
    $gdir/ws-keys.i3   \
	$cdir/nav-keys.i3  \
	$cdir/key-bind.i3  \
	$cdir/prog-spes.i3 \
	$cdir/xf86-keys.i3 \
	$cdir/footer.i3    \
    | rmc > $cdir/config;

< $cdir/config keybindings \
    > "$gdir/keybindings"

< "$gdir/keybindings" key_conflicts
