#!/bin/sh

cdir=$HOME/.config/i3/

cat $cdir/config.base 	\
		$cdir/config.nav-keys 	\
		$cdir/config.key-bind 	\
		$cdir/config.xf86-keys \
		$cdir/config.footer 	\
		| sed '{/^[ \t]*#/d;/^$/d; s/[ \t]*#%.*$//; s/[ \t]*$//}' \
		> $cdir/config

# TODO: Look for conflicts
cat $cdir/config | grep ^bindsym | sed 's/\t/ /' | cut -d' ' -f 2 > $cdir/keybindings



